CreateColorGTD(playerid)
{
	//Color Game - KUSH
	ColorGTD[playerid][0] = CreatePlayerTextDraw(playerid, 321.000000, 183.000000, "_");
	PlayerTextDrawFont(playerid, ColorGTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, ColorGTD[playerid][0], 0.600000, 7.300003);
	PlayerTextDrawTextSize(playerid, ColorGTD[playerid][0], 298.500000, 209.000000);
	PlayerTextDrawSetOutline(playerid, ColorGTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, ColorGTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, ColorGTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, ColorGTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, ColorGTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, ColorGTD[playerid][0], 255);
	PlayerTextDrawUseBox(playerid, ColorGTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, ColorGTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, ColorGTD[playerid][0], 0);

	rol1[playerid] = CreatePlayerTextDraw(playerid, 252.000000, 187.000000, "_");
	PlayerTextDrawFont(playerid, rol1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, rol1[playerid], 0.600000, 6.400001);
	PlayerTextDrawTextSize(playerid, rol1[playerid], 298.500000, 60.000000);
	PlayerTextDrawSetOutline(playerid, rol1[playerid], 2);
	PlayerTextDrawSetShadow(playerid, rol1[playerid], 0);
	PlayerTextDrawAlignment(playerid, rol1[playerid], 2);
	PlayerTextDrawColor(playerid, rol1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, rol1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, rol1[playerid], -16776961);
	PlayerTextDrawUseBox(playerid, rol1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, rol1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, rol1[playerid], 0);

	rol2[playerid] = CreatePlayerTextDraw(playerid, 321.000000, 187.000000, "_");
	PlayerTextDrawFont(playerid, rol2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, rol2[playerid], 0.600000, 6.400001);
	PlayerTextDrawTextSize(playerid, rol2[playerid], 298.500000, 60.000000);
	PlayerTextDrawSetOutline(playerid, rol2[playerid], 3);
	PlayerTextDrawSetShadow(playerid, rol2[playerid], 0);
	PlayerTextDrawAlignment(playerid, rol2[playerid], 2);
	PlayerTextDrawColor(playerid, rol2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, rol2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, rol2[playerid], -1);
	PlayerTextDrawUseBox(playerid, rol2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, rol2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, rol2[playerid], 0);

	rol3[playerid] = CreatePlayerTextDraw(playerid, 390.000000, 187.000000, "_");
	PlayerTextDrawFont(playerid, rol3[playerid], 1);
	PlayerTextDrawLetterSize(playerid, rol3[playerid], 0.600000, 6.400001);
	PlayerTextDrawTextSize(playerid, rol3[playerid], 298.500000, 60.000000);
	PlayerTextDrawSetOutline(playerid, rol3[playerid], 1);
	PlayerTextDrawSetShadow(playerid, rol3[playerid], 0);
	PlayerTextDrawAlignment(playerid, rol3[playerid], 2);
	PlayerTextDrawColor(playerid, rol3[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, rol3[playerid], 255);
	PlayerTextDrawBoxColor(playerid, rol3[playerid], 8388863);
	PlayerTextDrawUseBox(playerid, rol3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, rol3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, rol3[playerid], 0);

	ColorGTD[playerid][1] = CreatePlayerTextDraw(playerid, 322.000000, 142.000000, "COLOR GAME");
	PlayerTextDrawFont(playerid, ColorGTD[playerid][1], 2);
	PlayerTextDrawLetterSize(playerid, ColorGTD[playerid][1], 0.600000, 2.899996);
	PlayerTextDrawTextSize(playerid, ColorGTD[playerid][1], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ColorGTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, ColorGTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, ColorGTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, ColorGTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, ColorGTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, ColorGTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, ColorGTD[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, ColorGTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, ColorGTD[playerid][1], 0);

	ColorGTD[playerid][2] = CreatePlayerTextDraw(playerid, 321.000000, 283.000000, "_");
	PlayerTextDrawFont(playerid, ColorGTD[playerid][2], 1);
	PlayerTextDrawLetterSize(playerid, ColorGTD[playerid][2], 0.600000, 5.799994);
	PlayerTextDrawTextSize(playerid, ColorGTD[playerid][2], 298.500000, 313.000000);
	PlayerTextDrawSetOutline(playerid, ColorGTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, ColorGTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, ColorGTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, ColorGTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, ColorGTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, ColorGTD[playerid][2], 255);
	PlayerTextDrawUseBox(playerid, ColorGTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, ColorGTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, ColorGTD[playerid][2], 0);

	bet2[playerid] = CreatePlayerTextDraw(playerid, 294.000000, 287.000000, "_");
	PlayerTextDrawFont(playerid, bet2[playerid], 1);
	PlayerTextDrawLetterSize(playerid, bet2[playerid], 0.600000, 4.849995);
	PlayerTextDrawTextSize(playerid, bet2[playerid], 50.000000, 45.000000);
	PlayerTextDrawSetOutline(playerid, bet2[playerid], 1);
	PlayerTextDrawSetShadow(playerid, bet2[playerid], 0);
	PlayerTextDrawAlignment(playerid, bet2[playerid], 2);
	PlayerTextDrawColor(playerid, bet2[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, bet2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, bet2[playerid], -1);
	PlayerTextDrawUseBox(playerid, bet2[playerid], 1);
	PlayerTextDrawSetProportional(playerid, bet2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, bet2[playerid], 1);

	bet3[playerid] = CreatePlayerTextDraw(playerid, 346.000000, 287.000000, "_");
	PlayerTextDrawFont(playerid, bet3[playerid], 1);
	PlayerTextDrawLetterSize(playerid, bet3[playerid], 0.600000, 4.849995);
	PlayerTextDrawTextSize(playerid, bet3[playerid], 50.000000, 45.000000);
	PlayerTextDrawSetOutline(playerid, bet3[playerid], 1);
	PlayerTextDrawSetShadow(playerid, bet3[playerid], 0);
	PlayerTextDrawAlignment(playerid, bet3[playerid], 2);
	PlayerTextDrawColor(playerid, bet3[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, bet3[playerid], 255);
	PlayerTextDrawBoxColor(playerid, bet3[playerid], 8388863);
	PlayerTextDrawUseBox(playerid, bet3[playerid], 1);
	PlayerTextDrawSetProportional(playerid, bet3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, bet3[playerid], 1);

	bet4[playerid] = CreatePlayerTextDraw(playerid, 398.000000, 287.000000, "_");
	PlayerTextDrawFont(playerid, bet4[playerid], 1);
	PlayerTextDrawLetterSize(playerid, bet4[playerid], 0.600000, 4.849995);
	PlayerTextDrawTextSize(playerid, bet4[playerid], 50.000000, 45.000000);
	PlayerTextDrawSetOutline(playerid, bet4[playerid], 1);
	PlayerTextDrawSetShadow(playerid, bet4[playerid], 0);
	PlayerTextDrawAlignment(playerid, bet4[playerid], 2);
	PlayerTextDrawColor(playerid, bet4[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, bet4[playerid], 255);
	PlayerTextDrawBoxColor(playerid, bet4[playerid], -1439470849);
	PlayerTextDrawUseBox(playerid, bet4[playerid], 1);
	PlayerTextDrawSetProportional(playerid, bet4[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, bet4[playerid], 1);

	bet1[playerid] = CreatePlayerTextDraw(playerid, 243.000000, 287.000000, "_");
	PlayerTextDrawFont(playerid, bet1[playerid], 1);
	PlayerTextDrawLetterSize(playerid, bet1[playerid], 0.600000, 4.849995);
	PlayerTextDrawTextSize(playerid, bet1[playerid], 50.000000, 45.000000);
	PlayerTextDrawSetOutline(playerid, bet1[playerid], 1);
	PlayerTextDrawSetShadow(playerid, bet1[playerid], 0);
	PlayerTextDrawAlignment(playerid, bet1[playerid], 2);
	PlayerTextDrawColor(playerid, bet1[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, bet1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, bet1[playerid], -16776961);
	PlayerTextDrawUseBox(playerid, bet1[playerid], 1);
	PlayerTextDrawSetProportional(playerid, bet1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, bet1[playerid], 1);

	ColorGTD[playerid][3] = CreatePlayerTextDraw(playerid, 322.000000, 262.000000, "Choose your color");
	PlayerTextDrawFont(playerid, ColorGTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, ColorGTD[playerid][3], 0.308333, 2.149996);
	PlayerTextDrawTextSize(playerid, ColorGTD[playerid][3], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ColorGTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, ColorGTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, ColorGTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, ColorGTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, ColorGTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, ColorGTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, ColorGTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, ColorGTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, ColorGTD[playerid][3], 0);

	ibet1[playerid] = CreatePlayerTextDraw(playerid, 243.000000, 300.000000, "BET");
	PlayerTextDrawFont(playerid, ibet1[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ibet1[playerid], 0.208333, 1.799998);
	PlayerTextDrawTextSize(playerid, ibet1[playerid], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ibet1[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ibet1[playerid], 1);
	PlayerTextDrawAlignment(playerid, ibet1[playerid], 2);
	PlayerTextDrawColor(playerid, ibet1[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, ibet1[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ibet1[playerid], 50);
	PlayerTextDrawUseBox(playerid, ibet1[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ibet1[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ibet1[playerid], 0);

	ibet2[playerid] = CreatePlayerTextDraw(playerid, 294.000000, 300.000000, "BET");
	PlayerTextDrawFont(playerid, ibet2[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ibet2[playerid], 0.208333, 1.799998);
	PlayerTextDrawTextSize(playerid, ibet2[playerid], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ibet2[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ibet2[playerid], 1);
	PlayerTextDrawAlignment(playerid, ibet2[playerid], 2);
	PlayerTextDrawColor(playerid, ibet2[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, ibet2[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ibet2[playerid], 50);
	PlayerTextDrawUseBox(playerid, ibet2[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ibet2[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ibet2[playerid], 0);

	ibet3[playerid] = CreatePlayerTextDraw(playerid, 346.000000, 300.000000, "BET");
	PlayerTextDrawFont(playerid, ibet3[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ibet3[playerid], 0.208333, 1.799998);
	PlayerTextDrawTextSize(playerid, ibet3[playerid], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ibet3[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ibet3[playerid], 1);
	PlayerTextDrawAlignment(playerid, ibet3[playerid], 2);
	PlayerTextDrawColor(playerid, ibet3[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, ibet3[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ibet3[playerid], 50);
	PlayerTextDrawUseBox(playerid, ibet3[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ibet3[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ibet3[playerid], 0);

	ibet4[playerid] = CreatePlayerTextDraw(playerid, 398.000000, 300.000000, "BET");
	PlayerTextDrawFont(playerid, ibet4[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ibet4[playerid], 0.208333, 1.799998);
	PlayerTextDrawTextSize(playerid, ibet4[playerid], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ibet4[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ibet4[playerid], 1);
	PlayerTextDrawAlignment(playerid, ibet4[playerid], 2);
	PlayerTextDrawColor(playerid, ibet4[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, ibet4[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ibet4[playerid], 50);
	PlayerTextDrawUseBox(playerid, ibet4[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ibet4[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ibet4[playerid], 0);

	ColorGTD[playerid][4] = CreatePlayerTextDraw(playerid, 322.000000, 165.000000, "CRP V0.5");
	PlayerTextDrawFont(playerid, ColorGTD[playerid][4], 2);
	PlayerTextDrawLetterSize(playerid, ColorGTD[playerid][4], 0.245830, 1.700000);
	PlayerTextDrawTextSize(playerid, ColorGTD[playerid][4], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ColorGTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, ColorGTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, ColorGTD[playerid][4], 2);
	PlayerTextDrawColor(playerid, ColorGTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, ColorGTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, ColorGTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, ColorGTD[playerid][4], 0);
	PlayerTextDrawSetProportional(playerid, ColorGTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, ColorGTD[playerid][4], 0);

	roll[playerid] = CreatePlayerTextDraw(playerid, 322.000000, 347.000000, "ROLL");
	PlayerTextDrawFont(playerid, roll[playerid], 2);
	PlayerTextDrawLetterSize(playerid, roll[playerid], 0.429165, 2.599997);
	PlayerTextDrawTextSize(playerid, roll[playerid], 400.000000, 52.000000);
	PlayerTextDrawSetOutline(playerid, roll[playerid], 1);
	PlayerTextDrawSetShadow(playerid, roll[playerid], 3);
	PlayerTextDrawAlignment(playerid, roll[playerid], 2);
	PlayerTextDrawColor(playerid, roll[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, roll[playerid], 255);
	PlayerTextDrawBoxColor(playerid, roll[playerid], 255);
	PlayerTextDrawUseBox(playerid, roll[playerid], 0);
	PlayerTextDrawSetProportional(playerid, roll[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, roll[playerid], 1);

	bet5[playerid] = CreatePlayerTextDraw(playerid, 191.000000, 287.000000, "_");
	PlayerTextDrawFont(playerid, bet5[playerid], 1);
	PlayerTextDrawLetterSize(playerid, bet5[playerid], 0.600000, 4.849995);
	PlayerTextDrawTextSize(playerid, bet5[playerid], 50.000000, 45.000000);
	PlayerTextDrawSetOutline(playerid, bet5[playerid], 1);
	PlayerTextDrawSetShadow(playerid, bet5[playerid], 0);
	PlayerTextDrawAlignment(playerid, bet5[playerid], 2);
	PlayerTextDrawColor(playerid, bet5[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, bet5[playerid], 255);
	PlayerTextDrawBoxColor(playerid, bet5[playerid], -65281);
	PlayerTextDrawUseBox(playerid, bet5[playerid], 1);
	PlayerTextDrawSetProportional(playerid, bet5[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, bet5[playerid], 1);

	bet6[playerid] = CreatePlayerTextDraw(playerid, 450.000000, 287.000000, "_");
	PlayerTextDrawFont(playerid, bet6[playerid], 1);
	PlayerTextDrawLetterSize(playerid, bet6[playerid], 0.600000, 4.849995);
	PlayerTextDrawTextSize(playerid, bet6[playerid], 50.000000, 45.000000);
	PlayerTextDrawSetOutline(playerid, bet6[playerid], 1);
	PlayerTextDrawSetShadow(playerid, bet6[playerid], 0);
	PlayerTextDrawAlignment(playerid, bet6[playerid], 2);
	PlayerTextDrawColor(playerid, bet6[playerid], -1);
	PlayerTextDrawBackgroundColor(playerid, bet6[playerid], 255);
	PlayerTextDrawBoxColor(playerid, bet6[playerid], 65535);
	PlayerTextDrawUseBox(playerid, bet6[playerid], 1);
	PlayerTextDrawSetProportional(playerid, bet6[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, bet6[playerid], 1);

	ibet6[playerid] = CreatePlayerTextDraw(playerid, 450.000000, 300.000000, "BET");
	PlayerTextDrawFont(playerid, ibet6[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ibet6[playerid], 0.208333, 1.799998);
	PlayerTextDrawTextSize(playerid, ibet6[playerid], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ibet6[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ibet6[playerid], 1);
	PlayerTextDrawAlignment(playerid, ibet6[playerid], 2);
	PlayerTextDrawColor(playerid, ibet6[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, ibet6[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ibet6[playerid], 50);
	PlayerTextDrawUseBox(playerid, ibet6[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ibet6[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ibet6[playerid], 0);

	ibet5[playerid] = CreatePlayerTextDraw(playerid, 191.000000, 299.000000, "BET");
	PlayerTextDrawFont(playerid, ibet5[playerid], 2);
	PlayerTextDrawLetterSize(playerid, ibet5[playerid], 0.208333, 1.799998);
	PlayerTextDrawTextSize(playerid, ibet5[playerid], 400.000000, 207.000000);
	PlayerTextDrawSetOutline(playerid, ibet5[playerid], 0);
	PlayerTextDrawSetShadow(playerid, ibet5[playerid], 1);
	PlayerTextDrawAlignment(playerid, ibet5[playerid], 2);
	PlayerTextDrawColor(playerid, ibet5[playerid], 16777215);
	PlayerTextDrawBackgroundColor(playerid, ibet5[playerid], 255);
	PlayerTextDrawBoxColor(playerid, ibet5[playerid], 50);
	PlayerTextDrawUseBox(playerid, ibet5[playerid], 0);
	PlayerTextDrawSetProportional(playerid, ibet5[playerid], 1);
	PlayerTextDrawSetSelectable(playerid, ibet5[playerid], 0);

	SetTimerEx("ShowColorG", 500, false, "i", playerid);
}