CreateEditToysTD(playerid)
{
		//Edit Toys
	EdittoysTD[playerid][0] = CreatePlayerTextDraw(playerid, 208.000000, 184.000000, "X");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][0], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][0], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][0], 0);

	EdittoysTD[playerid][1] = CreatePlayerTextDraw(playerid, 168.000000, 187.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][1], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][1], 1);

	EdittoysTD[playerid][2] = CreatePlayerTextDraw(playerid, 230.000000, 188.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][2], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][2], 1);

	EdittoysTD[playerid][3] = CreatePlayerTextDraw(playerid, 208.000000, 220.000000, "Y");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][3], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][3], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][3], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][3], 0);

	EdittoysTD[playerid][4] = CreatePlayerTextDraw(playerid, 230.000000, 223.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][4], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][4], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][4], 1);

	EdittoysTD[playerid][5] = CreatePlayerTextDraw(playerid, 168.000000, 223.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][5], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][5], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][5], 1);

	EdittoysTD[playerid][6] = CreatePlayerTextDraw(playerid, 230.000000, 257.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][6], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][6], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][6], 1);

	EdittoysTD[playerid][7] = CreatePlayerTextDraw(playerid, 168.000000, 256.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][7], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][7], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][7], 1);

	EdittoysTD[playerid][8] = CreatePlayerTextDraw(playerid, 208.000000, 252.000000, "Z");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][8], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][8], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][8], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][8], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][8], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][8], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][8], 0);

	EdittoysTD[playerid][9] = CreatePlayerTextDraw(playerid, 395.000000, 187.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][9], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][9], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][9], 1);

	EdittoysTD[playerid][10] = CreatePlayerTextDraw(playerid, 434.000000, 184.000000, "X");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][10], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][10], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][10], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][10], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][10], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][10], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][10], 0);

	EdittoysTD[playerid][11] = CreatePlayerTextDraw(playerid, 453.000000, 188.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][11], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][11], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][11], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][11], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][11], 1);

	EdittoysTD[playerid][12] = CreatePlayerTextDraw(playerid, 395.000000, 223.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][12], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][12], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][12], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][12], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][12], 1);

	EdittoysTD[playerid][13] = CreatePlayerTextDraw(playerid, 453.000000, 223.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][13], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][13], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][13], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][13], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][13], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][13], 1);

	EdittoysTD[playerid][14] = CreatePlayerTextDraw(playerid, 434.000000, 219.000000, "Y");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][14], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][14], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][14], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][14], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][14], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][14], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][14], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][14], 0);

	EdittoysTD[playerid][15] = CreatePlayerTextDraw(playerid, 395.000000, 256.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][15], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][15], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][15], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][15], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][15], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][15], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][15], 1);

	EdittoysTD[playerid][16] = CreatePlayerTextDraw(playerid, 453.000000, 256.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][16], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][16], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][16], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][16], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][16], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][16], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][16], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][16], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][16], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][16], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][16], 1);

	EdittoysTD[playerid][17] = CreatePlayerTextDraw(playerid, 434.000000, 253.000000, "Z");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][17], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][17], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][17], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][17], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][17], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][17], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][17], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][17], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][17], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][17], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][17], 0);

	EdittoysTD[playerid][18] = CreatePlayerTextDraw(playerid, 318.000000, 329.000000, "X");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][18], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][18], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][18], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][18], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][18], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][18], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][18], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][18], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][18], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][18], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][18], 0);

	EdittoysTD[playerid][19] = CreatePlayerTextDraw(playerid, 279.000000, 331.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][19], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][19], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][19], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][19], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][19], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][19], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][19], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][19], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][19], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][19], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][19], 1);

	EdittoysTD[playerid][20] = CreatePlayerTextDraw(playerid, 339.000000, 332.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][20], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][20], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][20], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][20], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][20], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][20], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][20], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][20], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][20], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][20], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][20], 1);

	EdittoysTD[playerid][21] = CreatePlayerTextDraw(playerid, 279.000000, 366.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][21], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][21], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][21], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][21], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][21], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][21], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][21], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][21], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][21], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][21], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][21], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][21], 1);

	EdittoysTD[playerid][22] = CreatePlayerTextDraw(playerid, 339.000000, 366.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][22], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][22], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][22], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][22], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][22], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][22], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][22], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][22], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][22], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][22], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][22], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][22], 1);

	EdittoysTD[playerid][23] = CreatePlayerTextDraw(playerid, 279.000000, 400.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][23], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][23], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][23], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][23], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][23], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][23], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][23], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][23], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][23], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][23], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][23], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][23], 1);

	EdittoysTD[playerid][24] = CreatePlayerTextDraw(playerid, 339.000000, 400.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][24], 4);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][24], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][24], 20.500000, 20.500000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][24], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][24], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][24], 1);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][24], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][24], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][24], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][24], 1);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][24], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][24], 1);

	EdittoysTD[playerid][25] = CreatePlayerTextDraw(playerid, 318.000000, 363.000000, "Y");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][25], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][25], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][25], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][25], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][25], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][25], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][25], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][25], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][25], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][25], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][25], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][25], 0);

	EdittoysTD[playerid][26] = CreatePlayerTextDraw(playerid, 318.000000, 398.000000, "Z");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][26], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][26], 0.720831, 2.449997);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][26], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][26], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][26], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][26], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][26], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][26], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][26], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][26], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][26], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][26], 0);

    EdittoysTD[playerid][27] = CreatePlayerTextDraw(playerid, 209.000000, 160.000000, "Position");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][27], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][27], 0.720830, 2.449996);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][27], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][27], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][27], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][27], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][27], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][27], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][27], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][27], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][27], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][27], 0);

	EdittoysTD[playerid][28] = CreatePlayerTextDraw(playerid, 318.000000, 307.000000, "Scale");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][28], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][28], 0.720830, 2.449996);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][28], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][28], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][28], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][28], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][28], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][28], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][28], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][28], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][28], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][28], 0);

	EdittoysTD[playerid][29] = CreatePlayerTextDraw(playerid, 434.000000, 161.000000, "Rotation");
	PlayerTextDrawFont(playerid, EdittoysTD[playerid][29], 1);
	PlayerTextDrawLetterSize(playerid, EdittoysTD[playerid][29], 0.720830, 2.449996);
	PlayerTextDrawTextSize(playerid, EdittoysTD[playerid][29], 400.000000, 17.000000);
	PlayerTextDrawSetOutline(playerid, EdittoysTD[playerid][29], 1);
	PlayerTextDrawSetShadow(playerid, EdittoysTD[playerid][29], 0);
	PlayerTextDrawAlignment(playerid, EdittoysTD[playerid][29], 2);
	PlayerTextDrawColor(playerid, EdittoysTD[playerid][29], -1);
	PlayerTextDrawBackgroundColor(playerid, EdittoysTD[playerid][29], 255);
	PlayerTextDrawBoxColor(playerid, EdittoysTD[playerid][29], 50);
	PlayerTextDrawUseBox(playerid, EdittoysTD[playerid][29], 0);
	PlayerTextDrawSetProportional(playerid, EdittoysTD[playerid][29], 1);
	PlayerTextDrawSetSelectable(playerid, EdittoysTD[playerid][29], 0);

	SetTimerEx("ShowToys", 500, false, "i", playerid);
}