ShowLockpick(playerid)
{
    //Lockpick - KUSH
	LockpickTD[playerid][0] = CreatePlayerTextDraw(playerid, 322.000000, 325.000000, "_");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][0], 1);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][0], 0.600000, 1.750000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][0], 298.500000, 165.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][0], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][0], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][0], 2);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][0], 1296911871);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][0], 0);

	LockpickTD[playerid][1] = CreatePlayerTextDraw(playerid, 322.000000, 328.000000, "_");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][1], 1);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][1], 0.600000, 1.150001);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][1], 298.500000, 160.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][1], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][1], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][1], 2);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][1], 255);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][1], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][1], 0);

	LockpickTD[playerid][2] = CreatePlayerTextDraw(playerid, 322.000000, 309.000000, "Lockpicking");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][2], 2);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][2], 0.250000, 1.350000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][2], 400.000000, 127.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][2], 2);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][2], 2);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][2], 0);

	LockpickTD[playerid][3] = CreatePlayerTextDraw(playerid, 322.000000, 344.000000, "PHASE 1");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][3], 2);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][3], 0.366665, 1.899999);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][3], 400.000000, 127.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][3], 2);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][3], 2);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][3], 0);

	LockpickTD[playerid][4] = CreatePlayerTextDraw(playerid, 243.000000, 327.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][4], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][4], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][4], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][4], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][4], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][4], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][4], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][4], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][4], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][4], 0);

	LockpickTD[playerid][5] = CreatePlayerTextDraw(playerid, 257.000000, 327.000000, "ld_beat:up");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][5], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][5], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][5], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][5], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][5], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][5], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][5], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][5], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][5], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][5], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][5], 0);

	LockpickTD[playerid][6] = CreatePlayerTextDraw(playerid, 272.000000, 327.000000, "ld_beat:down");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][6], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][6], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][6], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][6], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][6], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][6], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][6], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][6], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][6], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][6], 0);

	LockpickTD[playerid][7] = CreatePlayerTextDraw(playerid, 286.000000, 327.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][7], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][7], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][7], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][7], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][7], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][7], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][7], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][7], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][7], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][7], 0);

	LockpickTD[playerid][8] = CreatePlayerTextDraw(playerid, 301.000000, 327.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][8], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][8], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][8], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][8], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][8], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][8], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][8], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][8], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][8], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][8], 0);

	LockpickTD[playerid][9] = CreatePlayerTextDraw(playerid, 315.000000, 327.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][9], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][9], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][9], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][9], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][9], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][9], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][9], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][9], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][9], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][9], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][9], 0);

	LockpickTD[playerid][10] = CreatePlayerTextDraw(playerid, 329.000000, 327.000000, "ld_beat:up");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][10], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][10], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][10], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][10], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][10], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][10], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][10], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][10], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][10], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][10], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][10], 0);

	LockpickTD[playerid][11] = CreatePlayerTextDraw(playerid, 344.000000, 327.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][11], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][11], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][11], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][11], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][11], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][11], 2);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][11], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][11], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][11], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][11], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][11], 0);

	LockpickTD[playerid][12] = CreatePlayerTextDraw(playerid, 359.000000, 327.000000, "ld_beat:down");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][12], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][12], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][12], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][12], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][12], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][12], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][12], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][12], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][12], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][12], 0);

	LockpickTD[playerid][13] = CreatePlayerTextDraw(playerid, 374.000000, 327.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][13], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][13], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][13], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][13], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][13], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][13], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][13], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][13], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][13], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][13], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][13], 0);

	LockpickTD[playerid][14] = CreatePlayerTextDraw(playerid, 389.000000, 327.000000, "ld_beat:down");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][14], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][14], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][14], 11.500000, 12.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][14], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][14], 1);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][14], 1);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][14], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][14], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][14], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][14], 1);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][14], 0);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][14], 0);

	LockpickTD[playerid][15] = CreatePlayerTextDraw(playerid, 383.000000, 313.000000, "Timer: 10");
	PlayerTextDrawFont(playerid, LockpickTD[playerid][15], 2);
	PlayerTextDrawLetterSize(playerid, LockpickTD[playerid][15], 0.204165, 0.899999);
	PlayerTextDrawTextSize(playerid, LockpickTD[playerid][15], 400.000000, 127.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD[playerid][15], 1);
	PlayerTextDrawSetShadow(playerid, LockpickTD[playerid][15], 2);
	PlayerTextDrawAlignment(playerid, LockpickTD[playerid][15], 2);
	PlayerTextDrawColor(playerid, LockpickTD[playerid][15], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD[playerid][15], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD[playerid][15], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD[playerid][15], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD[playerid][15], 0);

	LockpickTD1[playerid][0] = CreatePlayerTextDraw(playerid, 171.000000, 341.000000, "ld_beat:down");
	PlayerTextDrawFont(playerid, LockpickTD1[playerid][0], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD1[playerid][0], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD1[playerid][0], 26.500000, 31.500000);
	PlayerTextDrawSetOutline(playerid, LockpickTD1[playerid][0], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD1[playerid][0], 0);
	PlayerTextDrawAlignment(playerid, LockpickTD1[playerid][0], 2);
	PlayerTextDrawColor(playerid, LockpickTD1[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD1[playerid][0], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD1[playerid][0], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD1[playerid][0], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD1[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD1[playerid][0], 1);

	LockpickTD1[playerid][1] = CreatePlayerTextDraw(playerid, 171.000000, 281.000000, "ld_beat:up");
	PlayerTextDrawFont(playerid, LockpickTD1[playerid][1], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD1[playerid][1], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD1[playerid][1], 26.500000, 29.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD1[playerid][1], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD1[playerid][1], 0);
	PlayerTextDrawAlignment(playerid, LockpickTD1[playerid][1], 2);
	PlayerTextDrawColor(playerid, LockpickTD1[playerid][1], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD1[playerid][1], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD1[playerid][1], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD1[playerid][1], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD1[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD1[playerid][1], 1);

	LockpickTD1[playerid][2] = CreatePlayerTextDraw(playerid, 195.000000, 312.000000, "ld_beat:right");
	PlayerTextDrawFont(playerid, LockpickTD1[playerid][2], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD1[playerid][2], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD1[playerid][2], 27.500000, 29.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD1[playerid][2], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD1[playerid][2], 0);
	PlayerTextDrawAlignment(playerid, LockpickTD1[playerid][2], 2);
	PlayerTextDrawColor(playerid, LockpickTD1[playerid][2], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD1[playerid][2], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD1[playerid][2], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD1[playerid][2], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD1[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD1[playerid][2], 1);

	LockpickTD1[playerid][3] = CreatePlayerTextDraw(playerid, 145.000000, 312.000000, "ld_beat:left");
	PlayerTextDrawFont(playerid, LockpickTD1[playerid][3], 4);
	PlayerTextDrawLetterSize(playerid, LockpickTD1[playerid][3], 0.600000, 2.000000);
	PlayerTextDrawTextSize(playerid, LockpickTD1[playerid][3], 29.000000, 29.000000);
	PlayerTextDrawSetOutline(playerid, LockpickTD1[playerid][3], 2);
	PlayerTextDrawSetShadow(playerid, LockpickTD1[playerid][3], 0);
	PlayerTextDrawAlignment(playerid, LockpickTD1[playerid][3], 2);
	PlayerTextDrawColor(playerid, LockpickTD1[playerid][3], -1);
	PlayerTextDrawBackgroundColor(playerid, LockpickTD1[playerid][3], 255);
	PlayerTextDrawBoxColor(playerid, LockpickTD1[playerid][3], 50);
	PlayerTextDrawUseBox(playerid, LockpickTD1[playerid][3], 0);
	PlayerTextDrawSetProportional(playerid, LockpickTD1[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, LockpickTD1[playerid][3], 1);

    SetTimerEx("ShowAllLockpick", 500, false, "i", playerid);
    return 1;
}